#CloudFormation Template for wordpress site
#Author: BP
Mappings:
  mRegionMap:
    us-east-1:
      AMI: ami-1853ac65
    us-west-1:
      AMI: ami-bf5540df
    eu-west-1:
      AMI: ami-3bfab942
    ap-southeast-1:
      AMI: ami-e2adf99e
    ap-southeast-2:
      AMI: ami-43874721
  mEnvironment:
    Micro:
      db: db.t2.micro
      instance: t2.micro
    Small:
      db: db.t2.small
      instance: t2.small
    Medium:
      db: db.t2.medium
      instance: t2.medium
Parameters:
  pKeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Enter existing key pair
  pEnvironmentSize:
    Type: String
    AllowedValues:
      - Micro
      - Small
      - Medium
    Default: Micro
    Description: Select environment 
  pDBName:
    Type: String
    Default: dbwordpress
  pDBUser:
    Type: String
    Default: wpuser
  pDBPassword:
    Type: String
    Default: Welcome!
Resources:
  cSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow inbound SSH Traffic port 22 tcp"
  cInstanceInboundRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      ToPort: 22
      FromPort: 22
      CidrIp: 0.0.0.0/0
      GroupId:  !GetAtt cSecurityGroup.GroupId
  cInstanceInboundRule2:
      Type: AWS::EC2::SecurityGroupIngress
      Properties:
        IpProtocol: tcp
        ToPort: 80
        FromPort: 80
        CidrIp: 0.0.0.0/0
        GroupId: !GetAtt cSecurityGroup.GroupId
  cEc2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType:
        !FindInMap
          - mEnvironment
          - !Ref pEnvironmentSize
          - instance  
      ImageId: 
        !FindInMap
          - mRegionMap
          - !Ref AWS::Region
          - 'AMI'
      UserData:
        'Fn::Base64':
          !Sub |
            #!/bin/bash  
            sudo yum -y install epel-release
            sudo yum-config-manager --enable remi-php72
            yum update -y && yum -y install httpd php mysql php-mysql && yum update -y
            chkconfig httpd on
            service httpd start
            cd /var/www/html
            wget https://wordpress.org/wordpress-4.9.3.tar.gz
            tar -zxvf wordpress-4.9.3.tar.gz --strip 1
            rm wordpress-4.9.3.tar.gz
            cp wp-config-sample.php wp-config.php
            sed -i 's/database_name_here/${pDBName}/g' wp-config.php
            sed -i 's/localhost/${cDbInstance.Endpoint.Address}/g' wp-config.php
            sed -i 's/username_here/${pDBUser}/g' wp-config.php
            sed -i 's/password_here/${pDBPassword}/g' wp-config.php
      SecurityGroups:
        - !Ref cSecurityGroup
      KeyName: !Ref pKeyPair
      Tags:
        - Key: Name
          Value: cf-ec2-wordpress
  cDbInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 5
      DBInstanceClass: 
        !FindInMap
          - mEnvironment
          - !Ref pEnvironmentSize
          - db
      DBName: !Ref pDBName
      Engine: MySQL
      MasterUsername: !Ref pDBUser
      MasterUserPassword: !Ref pDBPassword
      StorageType: gp2
      Tags:
        - Key: Name
          Value: cfn-wordpress-db--server
