# Author: Birju 
# enable versioning on bucket and adding lifecycle configuration on objects
Parameters:
  BucketName:
    Type: String
    Description: Enter bucket name. Prefix is custom-s3-YOURBUCKETNAME-AccountId
    Type: String
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 
        !Join
          - ''
          - - 'custom-s3-cloudformation-'
            - !Ref BucketName
            - '-'
            - !Ref AWS::AccountId
      AccessControl: PublicRead
      WebsiteConfiguration:
        ErrorDocument: error.html
        IndexDocument: index.html
          
      Tags: 
        - Key: Name
          Value: 
            !Join
              - ''
              - - 'custom-s3-cloudformation-'
                - !Ref BucketName
                - '-'
                - !Ref AWS::AccountId            
Outputs:
  bucketname:
    Description: Bucket Name
    Value: !Ref BucketName