# Author: Birju 
# enable versioning on bucket and adding lifecycle configuration on objects
Parameters:
  BucketName:
    Type: String
    Description: Enter bucket name. Prefix is custom-s3-YOURBUCKETNAME-AccountId
    Type: String
  EnableVersioning:
    Description: enable versioning
    Type: String
    AllowedValues:
      - Enabled
      - Suspended
    Default: Enabled
  LifecycleConfig:
    Type: String
    Description: Enter number of days to move objects
    Default: 30
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 
        !Join
          - ''
          - - 'custom-s3-cloudformation-'
            - !Ref BucketName
            - '-'
            - !Ref AWS::AccountId
      AccessControl: PublicRead
      VersioningConfiguration:
        Status: !Ref EnableVersioning
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: !Ref LifecycleConfig
            Id: expiration in 30 days
            Status: Enabled
            NoncurrentVersionTransitions: 
              - 
                StorageClass: STANDARD_IA
                TransitionInDays: 30
          - Id: Noncurrent version in 30 days
            NoncurrentVersionExpirationInDays: !Ref LifecycleConfig
            Status: Enabled
      Tags: 
        - Key: Name
          Value: 
            !Join
              - ''
              - - 'custom-s3-cloudformation-'
                - !Ref BucketName
                - '-'
                - !Ref AWS::AccountId            
Outputs:
  bucketname:
    Description: Bucket Name
    Value: !Ref BucketName